version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      # Add other environment variables here
      # - DEEPSEEK_API_KEY=your_key_here
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
